FROM python:3.11 AS backend-local

WORKDIR /

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

RUN apt-get update
RUN apt-get -y install nginx

COPY startup.sh /
RUN chmod +x /startup.sh

WORKDIR /usr/src

EXPOSE 80

CMD ["/startup.sh"]

